goods/urls.py
from django.conf.urls import url
from .views import shop_main
from .views import add_cart
from .views import show_cart
from .views import remove_cart
from .views import update_cart
from .views import current_cart
from .views import clear_cart
from .views import payment
from .views import korea_bank_payment
from .views import thank_you
from .views import orderlist
from .views import get_my_order

urlpatterns = [
    url(r'^bank_payment/(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', korea_bank_payment, name='korea_bank_payment'),
    url(r'^add/$', add_cart, name='shopping-cart-add'),
    url(r'^show/$', show_cart, name='shopping-cart-show'),
    url(r'^remove/$', remove_cart, name='shopping-cart-remove'),
    url(r'^update/$', update_cart, name='shopping-cart-update'),
    url(r'^current/$', current_cart, name='shopping-cart-current'),
    url(r'^clear/$', clear_cart, name='shopping-cart-clear'),
    url(r'^payment/$', payment, name='payment'),
    url(r'^thankyou/(?P<order_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$', thank_you, name='thank-you'),
    url(r'^orderlist/$', orderlist, name='orderlist'),
    url(r'^my_orders/$', get_my_order, name='get_my_order'),
    url(r'^', shop_main, name='shop_main'),
]

irkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login,
        {'template_name': 'login_page/login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
    url('', include('social_django.urls', namespace='social')), # 이 줄을 등록해주면 됩니다.
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^ht/', include('health_check.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^shop/', include('goods.urls', namespace='shop')),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns += [
                       url(r'^__debug__/', include(debug_toolbar.urls)),
                       url(r'^uploads/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
                   ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/shopping/shopping-cart.html
{% load staticfiles %}
{% load carton_tags %}
{% get_cart as cart %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>Cart | VIA NOIR | IRK Shop</title>
    <meta name="description" content="Prepare for the battle before VIA NOIR XM Anomaly, with us."/>
    <link rel="stylesheet" type="text/css" href="{% static 'modal/css/style_cart.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'modal/css/component.css' %}"/>
    <style>
        @media (max-width: 640px) {
            .mobile-disabled {
                display: none;
            }
        }
    </style>
    <link rel="stylesheet" href="{% static 'modal/css/spinner.css' %}">
</head>
<body class="cart-modal">
<header class="cart-header mobile-disabled">
    <div class="cart-headerwrap">
        <div class="cart-logo">
            <!-- shopping cart image, H x W: 50 x 50 px -->
            <img src="{% static 'modal/images/icons/shopping_cart.png' %}" alt="shopping cart icon">
        </div>
        <div class="cart-title">
            <!-- title -->
            <h1>I R K&nbsp;&nbsp;S H O P</h1>
        </div>
    </div>
    <hr>
</header>
<div id="cart-mainwrap">
    <div id="cart-subtitle">
        <h2>Your shopping cart:</h2>
    </div>
    <table class="cart-data-table">
        <thead>
        <tr>
            <th class="cart-left cart-table-index">
                Item
            </th>
            <th class="cart-left cart-table-index mobile-disabled">
                <!-- item description -->
                &nbsp;
            </th>
            <th class="cart-left cart-table-index">
                Price
            </th>
            <th class="cart-center cart-table-index">
                Qty
            </th>
            <th class="cart-left cart-table-index">
                Subtotal
            </th>
            <th class="cart-center cart-table-index">
                Remove
            </th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart.items %}
            <tr>
                <td hidden class="item-values">
                    <div hidden class="cart-item-id">{{ item.product.id }}</div>
                    <div hidden class="cart-item-name">{{ item.product.name }}</div>
                    <div hidden class="cart-item-price">{{ item.product.price }}</div>
                    <div hidden class="cart-item-subtotal">{{ item.subtotal }}</div>
                </td>
                <td class="cart-left cart-item-view-image mobile-disabled">
                    <!-- thumbnail image, H x W: 50 x 50 px -->
                    <a href="/#SHOP{{ item.product.category }}/{{ item.product.id }}"
                       class="item-image iziModal-button-close">
                        {% if item.product.get_first_image %}
                            <img src="{{ item.product.get_first_image.image.url }}" alt="name of item here"
                                 style="width: 50px; height: auto;">
                        {% endif %}
                    </a>
                </td>
                <td class="cart-left cart-item-view-name">
                    <h3 class="item-name">
                        <!-- name of item, with link -->
                        <a href="/#SHOP{{ item.product.category }}/{{ item.product.id }}">{{ item.product.name }}</a>
                    </h3>
                </td>
                <td class="cart-left cart-price">
                    <!-- item price, per one -->
                    ${{ item.product.price }}
                </td>
                <td class="cart-center cart-item-view-qty">
                    <!-- quantity -->
                    <form>
                        {% csrf_token %}
                        <div hidden class="cart-item-id">{{ item.product.id }}</div>
                        <div hidden class="cart-item-name">{{ item.product.name }}</div>
                        <div hidden class="cart-item-price">{{ item.product.price }}</div>
                        <div hidden class="cart-item-subtotal">{{ item.subtotal }}</div>
                        <input value="{{ item.quantity }}" size="4" class="qty update-quantity" min="1" pattern="[0-9]+"
                               type="number">
                    </form>
                </td>
                <td class="cart-left cart-price cart-subtotal-each">
                    <!-- item price, subtotal -->
                    ${{ item.subtotal }}
                </td>
                <td id="btn-click" class="cart-center cart-item-remove">
                    <!-- remove button, animated -->
                    <button class="btn btn-animated btn-d btn-icon-only icon-remove">Remove</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <!-- total price area -->
        <tr>
            <td colspan="10" class="cart-right">
                <div class="cart-total-price" id="total_price">
                    Total: ${{ cart.total }}
                </div>
            </td>
        </tr>
        <!-- button area -->
        <tr>
            <td colspan="10" class="cart-buttons" id="btn-click">
                <div class="cart-buttons-wrapper">
                    <div class="cart-empty">
                        <button class="btn btn-animated btn-b icon-remove" id="cart-empty-btn">Empty Cart</button>
                    </div>
                    <div class="cart-checkout">
                        <button class="btn btn-animated btn-a icon-truck" id="checkout-btn"
                                onclick="window.top.location.href='{% url 'shop:payment' %}'">
                            Checkout
                        </button>
                    </div>
                </div>
            </td>
        </tr>
        </tfoot>
    </table>
</div>

<div class="spinner">
    <div class="sk-circle1 sk-child"></div>
    <div class="sk-circle2 sk-child"></div>
    <div class="sk-circle3 sk-child"></div>
    <div class="sk-circle4 sk-child"></div>
    <div class="sk-circle5 sk-child"></div>
    <div class="sk-circle6 sk-child"></div>
    <div class="sk-circle7 sk-child"></div>
    <div class="sk-circle8 sk-child"></div>
    <div class="sk-circle9 sk-child"></div>
    <div class="sk-circle10 sk-child"></div>
    <div class="sk-circle11 sk-child"></div>
    <div class="sk-circle12 sk-child"></div>
</div>

<script src="{% static 'modal/js/modernizr.custom.js' %}"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'modal/js/classie.js' %}"></script>
<script type="text/javascript">
    $('.update-quantity').on('change', function () {
        var spinner = $('.spinner')
        spinner.show()

        var input_value = $(this).val();
        var price = Number($(this).siblings('.cart-item-price').text())
        var total_price = input_value * price
        var good = Number($(this).siblings('.cart-item-id').text());

        $(this).parent().parent().siblings('.cart-subtotal-each').text('$' + total_price)

        $.ajax({
            url: "{% url 'shop:shopping-cart-update' %}",
            type: "POST",
            data: {
                'quantity': input_value,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'good': good
            },
            success: function (json) {
                $('#total_price').html('TotalPrice: $' + json['total'])
                spinner.hide()
            }
        })
    });

    $('.cart-item-remove').click(function () {
        var ok = confirm('Do you want to delete this product?')
        if (ok) {
            var good = Number($(this).siblings('.item-values').children('.cart-item-id').text());
            $.ajax({
                url: "{% url 'shop:shopping-cart-remove' %}",
                type: "POST",
                data: {
                    'good': good,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (json) {
                    location.reload();
                }
            })
        }
    })
    $('#cart-empty-btn').click(function () {
        var ok = confirm('Do you want to clear Shopping Cart?')
        if (ok) {
            $.ajax({
                url: "{% url 'shop:shopping-cart-clear' %}",
                type: "POST",
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (json) {
                    location.reload();
                }
            })
        }
    })
</script>

</body>
</html>