goods/urls.py
from django.conf.urls import url
from .views import shop_main
from .views import add_cart
from .views import show_cart
from .views import remove_cart
from .views import update_cart
from .views import current_cart
from .views import clear_cart
from .views import payment
from .views import korea_bank_payment
from .views import thank_you
from .views import orderlist
from .views import get_my_order

urlpatterns = [
    url(r'^bank_payment/(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', korea_bank_payment, name='korea_bank_payment'),
    url(r'^add/$', add_cart, name='shopping-cart-add'),
    url(r'^show/$', show_cart, name='shopping-cart-show'),
    url(r'^remove/$', remove_cart, name='shopping-cart-remove'),
    url(r'^update/$', update_cart, name='shopping-cart-update'),
    url(r'^current/$', current_cart, name='shopping-cart-current'),
    url(r'^clear/$', clear_cart, name='shopping-cart-clear'),
    url(r'^payment/$', payment, name='payment'),
    url(r'^thankyou/(?P<order_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$', thank_you, name='thank-you'),
    url(r'^orderlist/$', orderlist, name='orderlist'),
    url(r'^my_orders/$', get_my_order, name='get_my_order'),
    url(r'^', shop_main, name='shop_main'),
]

irkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login,
        {'template_name': 'login_page/login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
    url('', include('social_django.urls', namespace='social')), # 이 줄을 등록해주면 됩니다.
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^ht/', include('health_check.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^shop/', include('goods.urls', namespace='shop')),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns += [
                       url(r'^__debug__/', include(debug_toolbar.urls)),
                       url(r'^uploads/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
                   ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

goods/forms.py
from django import forms
from address.forms import AddressField

from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'ingress_mail',
            'ingress_agent_name',
            'is_shipping',
            'address',
            'additional_address',
            'custom_order',
            'bank_transfer_name',

        ]

    ingress_mail = forms.CharField(max_length=200, required=True)
    ingress_agent_name = forms.CharField(max_length=200, required=True)
    is_shipping = forms.widgets.boolean_check(v=None)
    address = AddressField(required=False)
    additional_address = forms.CharField(max_length=255, required=False)
    custom_order = forms.CharField(max_length=255, label='Order Options', required=False)
    bank_transfer_name = forms.CharField(max_length=20, required=False)
    how_to_receive_krw = forms.CharField(max_length=1, required=False)

goods/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.urls.base import reverse_lazy, reverse

from .models import Goods
from .models import Category
from .models import Order
from .models import OrderDetail
from .forms import OrderForm
# from .tasks import check_payment

from carton.cart import Cart
from django.contrib.auth.models import User

from core.send_mail import send_mail, send_gmail

from paypal.standard.forms import PayPalPaymentsForm
from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received

from simple_bank_korea import kb

import csv
from datetime import datetime
import requests
import json


def shop_main(request):
    categories = Category.objects.all().prefetch_related('goods_set').prefetch_related('goods_set__images')
    categories_list = []
    for i in categories:
        categories_list.append('SHOP' + i.name)
    # goods = Goods.objects.filter(is_valid=True).order_by('display_order')
    return render(request, 'goods/shop_main.html', {
        # 'goods': goods,
        'categories': categories,
        'categories_list': categories_list
    })


def add_cart(request):
    if request.method == 'POST':
        if request.is_ajax():
            cart = Cart(request.session)
            goods = Goods.objects.get(id=request.POST.get('good'))
            cart.add(goods, price=goods.price)
            return JsonResponse({
                'message': "Added {}".format(goods.name)
            })
    return JsonResponse({
        'message': "Please Access with AJAX/POST"
    })


def update_cart(request):
    if request.method == 'POST':
        if request.is_ajax():
            cart = Cart(request.session)
            quantity = request.POST.get('quantity')
            goods = Goods.objects.get(id=request.POST.get('good'))
            if not quantity:
                cart.set_quantity(goods, 0)
            else:
                cart.set_quantity(goods, quantity)
            return JsonResponse({
                'message': 'update {} for {}'.format(
                    goods.name, quantity
                ),
                'total': cart.total,
            })


def show_cart(request):
    cart = Cart(request.session)
    context = {"items": cart.items}
    return render(request, 'shopping/shopping-cart.html', context=context)


def current_cart(request):
    cart = Cart(request.session)
    return JsonResponse(dict(data=cart.items_serializable))


def remove_cart(request):
    if request.method == 'POST':
        if request.is_ajax():
            cart = Cart(request.session)
            goods = Goods.objects.get(pk=request.POST.get('good'))
            cart.remove(goods)
            return JsonResponse({
                'message': "Removed"
            })


def clear_cart(request):
    if request.method == 'POST':
        if request.is_ajax():
            cart = Cart(request.session)
            cart.clear()
            return JsonResponse({
                'message': 'cleared cart'
            })


@login_required
def payment(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        print(form.errors)
        if form.is_valid():
            this_order = form.save(commit=False)
            cart = Cart(request.session).cart_serializable
            payment_method = request.POST['payment-method']
            this_order.user = request.user
            if request.POST.get('shipping-options') == 'shipping':
                this_order.is_shipping = True
            this_order.save()
            order_number = this_order.pk
            for v in cart.values():
                order_detail = OrderDetail()
                order_detail.good = Goods.objects.get(pk=v['product_pk'])
                order_detail.count = v['quantity']
                order_detail.order = this_order
                order_detail.save()

            if payment_method == 'paypal':
                # paypal
                this_order.payment_method = 'p'
                this_order.save()
                if len(this_order.orderdetail_set.all()) > 1:
                    item_name = this_order.orderdetail_set.all()[0].good.name \
                                + this_order.orderdetail_set.all()[1].good.name + '...'
                else:
                    try:
                        item_name = this_order.orderdetail_set.all()[0].good.name
                    except IndexError:
                        return JsonResponse({
                            'message': 'Your order does NOT contain any goods.\n'
                                       'Add some goods and try again!',
                            'redirect': reverse('shop:shopping-cart-show')
                        })

                paypal_dict = {
                    "business": "{}".format(settings.PAYPAL_ID),
                    "amount": "{}".format(this_order.total_price),
                    "item_name": item_name,
                    "invoice": "{}".format(this_order.uuid),
                    "notify_url": settings.PAYPAL_URL + reverse('paypal-ipn'),
                    "return_url": settings.PAYPAL_URL + '/shop/thankyou/' + str(this_order.uuid),
                    "cancel_return": settings.PAYPAL_URL + reverse('shop:shop_main'),
                    "custom": "{}".format(this_order.user)
                }
                paypal_form = PayPalPaymentsForm(initial=paypal_dict).render()
                send_gmail(
                    send_to=str(this_order.user.email),
                    subject='IRKSHOP: Thankyou for your Order!',
                    order=this_order
                )
                # clear cart
                Cart(request.session).clear()
                return JsonResponse({
                    'message': "Sucessfully Ordered!\n"
                               "We've send you your order mail.\n"
                               "Please Continue with Paypal Payment.\n"
                               "(Paypal Checkout will show soon.)",
                    'paypal-form': paypal_form
                })
            elif payment_method == 'bank-transfer':
                # currency = requests.get('http://www.floatrates.com/daily/usd.json').text
                # today_usd_to_krw = int(json.loads(currency)['krw']['rate'] / 10) * 10
                this_order = Order.objects.get(pk=order_number)
                today_usd_to_krw = 1000
                this_order.payment_method = 'b'
                this_order.usd_to_krw = today_usd_to_krw
                this_order.bank_transfer_name = request.POST.get('bank_transfer_name')
                this_order.save()
                send_gmail(
                    send_to=str(this_order.user.email),
                    subject='IRKSHOP: Please Proceed Bank Transfer to finish your purchase',
                    order=this_order
                )
                # clear cart
                Cart(request.session).clear()
                return JsonResponse({
                    'message': "Sucessfully Ordered!\n"
                               "Please Continue with Bank Transfer.\n"
                               "We've mailed you our invoice.",
                    'redirect': '/shop/bank_payment/' + str(this_order.uuid) + '/'
                })
        else:
            return JsonResponse({
                'message': 'Order Form is not fully filled!\n'
                           'NOTE: Ingress Email and Agent Name are Required'
            })
    else:
        form = OrderForm()
    currency = requests.get('http://www.floatrates.com/daily/usd.json').text
    today_usd_to_krw = int(json.loads(currency)['krw']['rate'] / 10) * 10
    return render(request, 'payment/payment.html', {
        'form': form,
        'today_usd_to_krw': today_usd_to_krw
    })


@login_required
def get_my_order(request):
    my_orders = Order.objects.filter(user=request.user).prefetch_related('orderdetail_set')
    return render(request, 'my_orders.html', {
        'my_orders': my_orders
    })


# Paypal Payment Checking
@csrf_exempt
def check_payment(sender, **kwargs):
    ipn_obj = sender
    if ipn_obj.payment_status == ST_PP_COMPLETED:
        if ipn_obj.receiver_email != settings.PAYPAL_ID:
            return False
        try:
            order = Order.objects.get(uuid=ipn_obj.invoice)
            if ipn_obj.mc_gross == order.total_price:
                order.is_paid = True
                order.save()
                send_gmail(
                    send_to=order.user.email,
                    subject='IRKSHOP: Payment Confirmed!',
                    order=order
                )
                return True
        except:
            return False


@csrf_exempt
def cancel_payment(request):
    pass


@csrf_exempt
def thank_you(request, order_uuid):
    order = Order.objects.get(uuid=order_uuid)
    if order.is_paid:
        return render(request, 'mail_payment_confirm_template.html', {
            'order': order
        })
    else:
        if order.payment_method == 'p':
            paypal_dict = {
                "business": "{}".format(settings.PAYPAL_ID),
                "amount": "{}".format(order.total_price),
                "item_name": order.orderdetail_set.first().__str__() + '...',
                "invoice": "{}".format(order.uuid),
                "notify_url": settings.PAYPAL_URL + reverse('paypal-ipn'),
                "return_url": settings.PAYPAL_URL + '/shop/thankyou/' + str(order.uuid),
                "cancel_return": settings.PAYPAL_URL + reverse('shop:shop_main'),
                "custom": "{}".format(order.user)
            }
            paypal_form = PayPalPaymentsForm(initial=paypal_dict).render()
            data = {
                'order': order,

templates/goods/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load in_category %}
{% load carton_tags %}
{% get_cart as cart %}

{% block title %}IRK SHOP{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" xmlns="http://www.w3.org/1999/html">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.8.7/jquery.fullPage.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-social.css' %}">
    <link rel="stylesheet" href="{% static 'css/iziModal.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}
{% block body %}
    <div>
        {% include 'compositions/sidebar.html' %}
        <main>
            <img id="shopping-cart-icon" src="{% static 'image/shopping_cart.png' %}">
            <div id="modal" style="overflow: scroll; -webkit-overflow-scrolling: touch">
            </div>

            <div id="fullpage">
                {% for category in categories %}
                    <div class="section" id="{{ category }}">
                        {% for good in goods|in_category:category %}
                            {% if good|is_available %}
                                <div class="slide">
                                    <div class="box"
                                         style='background-image: url("{{ good.get_first_image.image.url }}");'>
                                        <div class="shadow-box">
                                            <div class="blank-box"></div>
                                            <div class="addCartButton-push">
                                                <img class="btn btn-xs addCartButton" name="submit"
                                                     src="{% static 'image/cart.png' %}">
                                                <h5>ADD TO CART</h5>
                                            </div>
                                            <form id="add{{ good.name|safe }}" class="addCart" method="POST"
                                                  enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <h2><strong>{{ good.name }}</strong></h2>
                                                <h4><u>Price: ${{ good.price }}</u></h4>
                                                <p>{{ good.description|safe }}</p>
                                                <input name="good" value="{{ good.pk }}" type="hidden">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </main>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
    <script src="{% static 'js/jquery.fullPage.min.js' %}"></script>
    <script src="{% static 'js/jquery.fullpage.extensions.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.8.7/vendors/scrolloverflow.min.js"></script>
    <script src="{% static 'js/iziModal.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#fullpage').fullpage({
                anchors: {{ categories_list|safe }},
                css3: true,
                navigation: true,
                navigationPosition: 'right',
                slidesToSections: true,
                slidesNavigation: true,
                loopHorizontal: false,
                controlArrows: true,
                onSlideLeave: function (anchorLink, index, slideIndex, direction, nextSlideIndex) {
                    $('.slider_prev').removeClass('slider_prev');
                    $('.slider_next').removeClass('slider_next')
                    var slides = $('div.active').children('.fp-slides')[0].children[0].children.length
                    console.log(slides)
                },
                afterSlideLoad: function (anchorLink, index, slideAnchor, slideIndex) {
                    var slides = $('div.active').children('.fp-slides')[0].children[0].children.length
                    console.log(slides)
                    if (length > 1) {
                        $('.fp-slide.active').next('.fp-slide').addClass('slider_next');
                        $('.fp-slide.active').prev('.fp-slide').addClass('slider_prev');
                    }
                }
            });

            $('.fp-slide.active').next('.fp-slide').addClass('slider_next');
            $('.fp-slide.active').prev('.fp-slide').addClass('slider_prev');

            window.closeModal = function closeModal(redirect_url) {
                $('#modal').iziModal('close');
                if (redirect_url) {
                    window.location.href = redirect_url
                }
            }
            $('#toggleHeader').click(function () {
                $('#header').toggleClass('open');
            })
            $('#fullpage').click(function () {
                $('#header').removeClass('open');
            })
            $('img.addCartButton').on('click touchstart', function () {
                var form = $(this).parent().next('form').serialize()
                $.ajax({
                    url: "{% url 'shopping-cart-add' %}",
                    type: "POST",
                    data: form,
                    success: function (json) {
                        console.log(json); // another sanity check
                        alert(json['message']);
                    }
                })
            });
            var current_width = Number(window.innerWidth)
            if (current_width < 600) {
                iframe_width = 480
            } else {
                iframe_width = current_width * 0.8
            }
            $("#modal").iziModal({
                iframe: true,
                iframeHeight: Number(window.innerHeight) * 0.9,
                iframeURL: "{% url 'shopping-cart-show' %}",
                width: iframe_width
            });
            console.log(window.innerWidth)
            console.log(window.innerHeight)
            $('#shopping-cart-icon').click(function () {
                $('#modal').iziModal('open'); // Use "this" to get URL href or option 'iframeURL'
            });
        });
    </script>
{% endblock %}

templates/goods/shop_main.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load in_category %}
{% load carton_tags %}
{% get_cart as cart %}

{% block title %}IRK SHOP{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" xmlns="http://www.w3.org/1999/html">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.8.7/jquery.fullPage.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-social.css' %}">
    <link rel="stylesheet" href="{% static 'css/iziModal.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}
{% block body %}
    <div>
        {% include 'compositions/sidebar.html' %}
        <main>
            <img id="shopping-cart-icon" src="{% static 'image/shopping_cart.png' %}">
            <div id="modal" style="overflow: scroll; -webkit-overflow-scrolling: touch">
                <button data-izimodal-close="" data-izimodal-transitionout="bounceOutDown">Close</button>
                <div class="iziModal-content"></div>
            </div>
            <div id="fullpage">
                {% for category in categories %}
                    <div class="section" id="{{ category }}">
                        {% for good in category.get_available_goods %}
                            <div class="slide">
                                <div class="box"
                                     style='background-image: url("{{ good.get_first_image.image.url }}");'>
                                    <div class="shadow-box">
                                        <div class="blank-box"></div>
                                        <div class="addCartButton-push">
                                            <img class="btn btn-xs addCartButton" name="submit"
                                                 src="{% static 'image/cart.png' %}">
                                            <h6>
                                                <small>{{ good.current_stock }} left</small>
                                            </h6>
                                            <h5>ADD TO CART</h5>
                                        </div>
                                        <form id="add{{ good.name|safe }}" class="addCart" method="POST"
                                              enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <h2><strong>{{ good.name }}</strong></h2>
                                            <h4><u>Price: ${{ good.price }}</u></h4>
                                            <p>{{ good.description|safe }}</p>
                                            <input name="good" value="{{ good.pk }}" type="hidden">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </main>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
    <script src="{% static 'js/jquery.fullPage.min.js' %}"></script>
    <script src="{% static 'js/jquery.fullpage.extensions.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.8.7/vendors/scrolloverflow.min.js"></script>
    <script src="{% static 'js/iziModal.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#fullpage').fullpage({
                anchors: {{ categories_list|safe }},
                css3: true,
                navigation: true,
                navigationPosition: 'right',
                slidesToSections: true,
                slidesNavigation: true,
                loopHorizontal: false,
                controlArrows: true,
                onSlideLeave: function (anchorLink, index, slideIndex, direction, nextSlideIndex) {
                    $('.slider_prev').removeClass('slider_prev');
                    $('.slider_next').removeClass('slider_next')
                    var slides = $('div.active').children('.fp-slides')[0].children[0].children.length
                    console.log(slides)
                },
                afterSlideLoad: function (anchorLink, index, slideAnchor, slideIndex) {
                    var slides = $('div.active').children('.fp-slides')[0].children[0].children.length
                    console.log(slides)
                    if (length > 1) {
                        $('.fp-slide.active').next('.fp-slide').addClass('slider_next');
                        $('.fp-slide.active').prev('.fp-slide').addClass('slider_prev');
                    }
                }
            });

            $('.fp-slide.active').next('.fp-slide').addClass('slider_next');
            $('.fp-slide.active').prev('.fp-slide').addClass('slider_prev');
            $('#toggleHeader').click(function () {
                $('#header').toggleClass('open');
            })
            $('#fullpage').click(function () {
                $('#header').removeClass('open');
            })
            $('img.addCartButton').on('click touchstart', function () {
                var form = $(this).parent().next('form').serialize()
                $.ajax({
                    url: "{% url 'shop:shopping-cart-add' %}",
                    type: "POST",
                    data: form,
                    success: function (json) {
                        console.log(json); // another sanity check
                        alert(json['message']);
                    }
                })
            });
        });
    </script>
    <script>
        var closeModal = function closeModal(redirect_url) {
            $('#modal').iziModal('close');
            if (redirect_url) {
                window.location.href = redirect_url
            }
        }
        var current_width = Number(window.innerWidth)
        if (current_width < 600) {
            iframe_width = 480
        } else {
            iframe_width = current_width * 0.8
        }
        $("#modal").iziModal({
            iframe: true,
            iframeHeight: Number(window.innerHeight) * 0.6,
            iframeURL: "{% url 'shop:shopping-cart-show' %}",
            width: iframe_width
        });
        $('#shopping-cart-icon').click(function () {
            $('#modal').iziModal('open'); // Use "this" to get URL href or option 'iframeURL'
        });
    </script>
{% endblock %}