goods/urls.py
from django.conf.urls import url
from .views import shop_main
from .views import add_cart
from .views import show_cart
from .views import remove_cart
from .views import update_cart
from .views import current_cart
from .views import clear_cart
from .views import payment
from .views import korea_bank_payment
from .views import thank_you
from .views import orderlist
from .views import get_my_order

urlpatterns = [
    url(r'^bank_payment/(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$', korea_bank_payment, name='korea_bank_payment'),
    url(r'^add/$', add_cart, name='shopping-cart-add'),
    url(r'^show/$', show_cart, name='shopping-cart-show'),
    url(r'^remove/$', remove_cart, name='shopping-cart-remove'),
    url(r'^update/$', update_cart, name='shopping-cart-update'),
    url(r'^current/$', current_cart, name='shopping-cart-current'),
    url(r'^clear/$', clear_cart, name='shopping-cart-clear'),
    url(r'^payment/$', payment, name='payment'),
    url(r'^thankyou/(?P<order_uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$', thank_you, name='thank-you'),
    url(r'^orderlist/$', orderlist, name='orderlist'),
    url(r'^my_orders/$', get_my_order, name='get_my_order'),
    url(r'^', shop_main, name='shop_main'),
]

irkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login,
        {'template_name': 'login_page/login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
    url('', include('social_django.urls', namespace='social')), # 이 줄을 등록해주면 됩니다.
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^ht/', include('health_check.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^shop/', include('goods.urls', namespace='shop')),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns += [
                       url(r'^__debug__/', include(debug_toolbar.urls)),
                       url(r'^uploads/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
                   ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
</head>
<body>
{% block body %}
{% endblock %}
<!-- jQuery -->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
{% block js %}{% endblock %}
<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: '172511599870594',
            xfbml: true,
            version: 'v2.6'
        });
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
</body>
</html>

templates/index.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>13MAGNUS Reawakens XM Anomaly--INGRESS Resistance Korea</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="robots" content="all,follow">

    <!-- Bootstrap and Font Awesome css-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Google fonts-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Pacifico">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,700">

    <!-- Theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" href="{% static 'css/backgroundTransition.css' %}">

    <!-- Custom stylesheet - for your changes-->
    <!-- Favicon-->
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>


    <!------------------------------------------------------------------------------>

    <style>

        #canvas {
            z-index: 1;
            width: 100%;
            height: auto;
            overflow: scroll;
            position: absolute;
            top: 0;
            left: 0;
        }

        .canvas-wrap {
            position: relative;
        }

        div.canvas-content {
            position: relative;
            z-index: 1;
            color: #0474B3;
            text-align: center;
            padding-top: 0;
        }

        /*--------------------------------------*/

        .link_set {
            z-index: 999 !important;
            clear: both;
        }

        .link_set ul li {
            font-size: inherit;
            text-align: center;
            color: #fff;
            letter-spacing: 1px;
            font-family: 'Philosopher', sans-serif;
            padding: 10px;
            list-style: none;
        }

        .link_set ul li a {
            text-align: center;
            color: #fff;
            letter-spacing: 1px;
            font-family: 'Philosopher', sans-serif;
            padding: 10px;
            text-decoration: none;
        }

        .link_set ul li a:hover {
            color: #FFF;
        }

        .cl-effect-1 a::before,
        .cl-effect-1 a::after {
            display: inline-block;
            opacity: 0;
            -webkit-transition: -webkit-transform 0.3s, opacity 0.2s;
            -moz-transition: -moz-transform 0.3s, opacity 0.2s;
            transition: transform 0.3s, opacity 0.2s;
        }

        .cl-effect-1 a::before {
            margin-right: 10px;
            content: '[';
            -webkit-transform: translateX(20px);
            -moz-transform: translateX(20px);
            transform: translateX(20px);
        }

        .cl-effect-1 a::after {
            margin-left: 10px;
            content: ']';
            -webkit-transform: translateX(-20px);
            -moz-transform: translateX(-20px);
            transform: translateX(-20px);
        }

        .cl-effect-1 a:hover::before,
        .cl-effect-1 a:hover::after,
        .cl-effect-1 a:focus::before,
        .cl-effect-1 a:focus::after {
            opacity: 1;
            -webkit-transform: translateX(0px);
            -moz-transform: translateX(0px);
            transform: translateX(0px);
        }

        ul, li {
            padding: 0;
            margin: 0;
        }

    </style>


    <!-------------------------------------------------------------------------->

</head>

<body>

<div class="backgroundTransition">

    <!------------------------------------------------------------------------------->

    <section class="canvas-wrap">
        <div class="canvas-content"><!--<h1>3D lines animation with three.js</h1>--></div>
        <div id="canvas" class="gradient"></div>
    </section>

    <!-- Main library -->
    <script src="{% static 'js1/three.min.js' %}"></script>

    <!-- Helpers -->
    <script src="{% static 'js1/projector.js' %}"></script>
    <script src="{% static 'js1/canvas-renderer.js' %}"></script>

    <!-- Visualitzation adjustments -->
    <script src="{% static 'js1/3d-lines-animation.js' %}"></script>

    <!-- Animated background color -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <!--<script src="js1/color.js"></script>-->

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>


    <!--------------------------------------------------------------------------------->

    <div class="main">
        <div class="overlay"></div>
        <div class="container">
            <p class="social">
                <a href="https://www.facebook.com/ingresskorea/" title="" class="facebook" target="_blank"><i
                        class="fa fa-facebook"></i></a>
                <a href="https://twitter.com/reskorea" title="" class="twitter" target="_blank"><i
                        class="fa fa-twitter"></i></a>
                <a href="https://plus.google.com/u/0/+IngressResistanceKorea" title="" class="gplus" target="_blank"
                   style="margin-right:0px;"><i class="fa fa-google-plus"></i></a>
                <!-- <a href="#" title="" class="instagram"><i class="fa fa-instagram"></i></a> --> <br><br>
                <img src="{% static 'img/ei.png' %}" width="10%" height="10%" alt=""/>

            </p>

            <div class="row">
                <div class="col-sm-12">
                    <h1 class="cursive">13MAGNUS Reawakens</h1>
                    <h2 class="sub">SEOUL</h2>
                </div>
            </div>

            <!-- countdown-->
            <div id="countdown" class="countdown">
                <div class="row">
                    <div class="countdown-item col-sm-3 col-xs-6">
                        <div id="countdown-days" class="countdown-number">&nbsp;</div>
                        <div class="countdown-label">days</div>
                    </div>
                    <div class="countdown-item col-sm-3 col-xs-6">
                        <div id="countdown-hours" class="countdown-number">&nbsp;</div>
                        <div class="countdown-label">hours</div>
                    </div>
                    <div class="countdown-item col-sm-3 col-xs-6">
                        <div id="countdown-minutes" class="countdown-number">&nbsp;</div>
                        <div class="countdown-label">minutes</div>
                    </div>
                    <div class="countdown-item col-sm-3 col-xs-6">
                        <div id="countdown-seconds" class="countdown-number">&nbsp;</div>
                        <div class="countdown-label">seconds</div>
                    </div>
                </div>
            </div>
            <!-- /.countdown-->


            <div class="link_set" style="margin: 20px auto">
                <nav class="cl-effect-1">
                    <ul>
                        <li>
                            <a href="https://13magnusseoul.splashthat.com/">NIA Registration</a>
                        </li>
                        <li>
                            <a href="http://register.seoul.willbe.blue">Resistance Registration</a>
                        </li>
                        <li>
                            <a href="{% url 'shop:shop_main' %}">IRK SWAG SHOP</a>
                        </li>
                        <li>
                            <a href="https://plus.google.com/u/1/communities/112385544333954788928">G+
                                Community</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>

        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <p>&copy;2017 <a href="http://cafe.naver.com/ingressresistance/" target="_blank">INGRESS
                            RESISTANCE KOREA</a></p>
                    </div>
                    <div class="col-md-6">
                        <p class="credit">IRK design team @HL2XIG / CC BY-NC-SA <br>
                            <small>
                                Theme by <a
                                    href="https://bootstrapious.com/tutorials" target="_blank">Bootstrapious</a>
                            </small>
                        </p>
                        <!-- Please do not remove the backlink to us unless you support the development at https://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :) -->
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- 배경 슬라이드 관련 자바스크립트 시작-->


    <script type="text/javascript" src="{% static 'js/backgroundTransition.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.backgroundTransition').backgroundTransition({
                backgrounds: [
                    {src: "{% static 'img/bg.jpg' %}"},
                    {src: "{% static 'img/bg1.jpg' %}"},
                    {src: "{% static 'img/bg2.jpg' %}"},
                    {src: "{% static 'img/bg3.jpg' %}"},
                    {src: "{% static 'img/bg4.jpg' %}"},
                    {src: "{% static 'img/bg5.jpg' %}"}
                ],
                transitionDelay: 3,
                animationSpeed: 1800
            });
        });
    </script>
    <!-- 배경 슬라이드 관련 자바스크립트 끝-->

</body>
</html>

templates/my_orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Orders</title>
</head>
<body>
    {{ my_orders }}
</body>
</html>